### ISSUE TITLE
忘记密码？

### ISSUE THREAD

**Issue by ShusenTang** [LEAFERx/hexo-leancloud-counter-security#12]
新增博客时部署失败，显示我的密码错误，但是我记得应该没错啊。怎样查看这个密码，就是之前执行以下命令时设置的密码：
```
hexo lc-counter register <<username>> <<password>>
```

```
ERROR The username and password mismatch. [400 POST https://th5bgglg.api.lncld.net/1.1/login]
Error: The username and password mismatch. [400 POST https://th5bgglg.api.lncld.net/1.1/login]
    at /Users/tangshusen/MyBlog/blog/node_modules/leancloud-storage/dist/node/request.js:163:17
    at tryCatch (/Users/tangshusen/MyBlog/blog/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/Users/tangshusen/MyBlog/blog/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at publish (/Users/tangshusen/MyBlog/blog/node_modules/es6-promise/dist/es6-promise.js:399:7)
    at publishRejection (/Users/tangshusen/MyBlog/blog/node_modules/es6-promise/dist/es6-promise.js:340:3)
    at flush (/Users/tangshusen/MyBlog/blog/node_modules/es6-promise/dist/es6-promise.js:128:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
INFO  Now syncing your posts list to leancloud counter...
INFO  Dealing with record of TensorFlow AttentionWrapper源码超详细图解
INFO  Deploy done: leancloud_counter_security_sync
ERROR Forbidden to create by class 'Counter' permissions. [403 POST https://th5bgglg.api.lncld.net/1.1/classes/Counter]
Error: Forbidden to create by class 'Counter' permissions. [403 POST https://th5bgglg.api.lncld.net/1.1/classes/Counter]
    at /Users/tangshusen/MyBlog/blog/node_modules/leancloud-storage/dist/node/request.js:163:17
    at tryCatch (/Users/tangshusen/MyBlog/blog/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/Users/tangshusen/MyBlog/blog/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at publish (/Users/tangshusen/MyBlog/blog/node_modules/es6-promise/dist/es6-promise.js:399:7)
    at publishRejection (/Users/tangshusen/MyBlog/blog/node_modules/es6-promise/dist/es6-promise.js:340:3)
    at flush (/Users/tangshusen/MyBlog/blog/node_modules/es6-promise/dist/es6-promise.js:128:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
leancloud.memo successfully updated.
```

**Comment by ShusenTang** [comment]
<img width="1323" alt="ddd" src="https://user-images.githubusercontent.com/16498688/54217679-0ca9b380-4527-11e9-8bf6-bd377f38122c.png">
这里可以修改密码，修改后就好了
