### ISSUE TITLE
how to add serverURL ??

### ISSUE THREAD

**Issue by 543877815** [LEAFERx/hexo-leancloud-counter-security#21]
When I tried to run register
`hexo lc-counter r username password`
It came out with the following error:
```
TypeError: serverURL option is required for apps from CN region
    at Object.init (D:\blog\node_modules\leancloud-storage\dist\node\init.js:92:13)
    at Hexo.commandFunc (D:\blog\node_modules\hexo-leancloud-counter-security\index.js:190:12)
    at Hexo.tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\blog\node_modules\bluebird\js\release\method.js:15:34)
    at D:\blog\node_modules\hexo\lib\hexo\index.js:187:15
    at Promise._execute (D:\blog\node_modules\bluebird\js\release\debuggability.js:313:9)
    at Promise._resolveFromExecutor (D:\blog\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (D:\blog\node_modules\bluebird\js\release\promise.js:79:10)
    at Hexo.call (D:\blog\node_modules\hexo\lib\hexo\index.js:183:10)
    at C:\Users\54387\AppData\Roaming\npm\node_modules\hexo-cli\lib\hexo.js:67:17
    at tryCatcher (C:\Users\54387\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\54387\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\Users\54387\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\Users\54387\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\54387\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (C:\Users\54387\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\54387\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\54387\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\54387\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate (internal/timers.js:456:21)
```

**Comment by stevenjoezhang** [comment]
Please read README.md before submitting issues, thanks!
https://github.com/theme-next/hexo-leancloud-counter-security#usage

And make sure you're using the latest version
```
npm i hexo-leancloud-counter-security@1.5.0
```

<blockquote><img src="https://avatars3.githubusercontent.com/u/32585093?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/theme-next/hexo-leancloud-counter-security">theme-next/hexo-leancloud-counter-security</a></strong></div><div>A plugin to fix a serious security bug in leancloud visitor counter for NexT. - theme-next/hexo-leancloud-counter-security</div></blockquote>

**Comment by zhongjiajie** [comment]
@543877815 我也遇到了这个问题，解决方式是配置成`https://leancloud.cn`

```yaml
leancloud_counter_security:
  enable_sync: true
  app_id: -
  app_key: -
  server_url: https://leancloud.cn
  username: admin
  password:
```
另外，如果中国区只有一个url的话，建议给一个示例给使用者，方便用户查阅@stevenjoezhang

**Comment by stevenjoezhang** [comment]
我不确定是否所有用户的 `server_url` 都是相同的，leancloud 的文档似乎没有说明。
当然，在 README 里面给个示例是没问题的，谢谢提醒！

**Comment by zhongjiajie** [comment]
我提了一个PR @stevenjoezhang

**Comment by 543877815** [comment]
@zhongjiajie 谢谢你！~
