### ISSUE TITLE
博客迁移到另一设备后无法同步

### ISSUE THREAD

**Issue by jimlee2048** [LEAFERx/hexo-leancloud-counter-security#23]
```
[32mINFO [39m Logined as: jimlee2002
[32mINFO [39m Now syncing your posts list to leancloud counter...
[41mFATAL[49m Something's wrong. Maybe you can find the solution here: [4mhttps://hexo.io/docs/troubleshooting.html[24m
[33mSyntaxError: Unexpected token , in JSON at position 59[39m
[33m    at JSON.parse (<anonymous>)[39m
[33m    at D:\Blog\node_modules\hexo-leancloud-counter-security\index.js:127:22[39m
[33m    at Array.forEach (<anonymous>)[39m
[33m    at Hexo.sync (D:\Blog\node_modules\hexo-leancloud-counter-security\index.js:121:20)[39m
[33m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[39m
```

**Comment by jimlee2002** [comment]
已尝试删除`/source/leancloud.demo`，问题依旧
