### ISSUE TITLE
Error in log output

### ISSUE THREAD

**Issue by ljcbaby** [LEAFERx/hexo-leancloud-counter-security#26]
```bash
hexo_root/node_modules/hexo-leancloud-counter-security/index.js:73
    this.log.info('leancloud.memo successfully updated.');
         ^

TypeError: Cannot read property 'log' of undefined
    at postOperation (hexo_root/node_modules/hexo-leancloud-counter-security/index.js:73:10)
    at /www/page/hexo/node_modules/hexo-leancloud-counter-security/index.js:160:17
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

```
➜  hexo git:(master) ✗ node -v
v15.8.0
➜  hexo git:(master) ✗ npm -v
7.6.0
➜  hexo git:(master) ✗ npm list --depth 0
hexo-site@0.0.0 /www/page/hexo
├── hexo-deployer-cos-cdn@1.7.1
├── hexo-deployer-git@3.0.0
├── hexo-filter-mathjax@0.6.3
├── hexo-generator-archive@1.0.0
├── hexo-generator-baidu-sitemap@0.1.9
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@3.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-search@2.4.1
├── hexo-generator-sitemap@2.1.0
├── hexo-generator-tag@1.0.0
├── hexo-lazyload-image@1.0.10
├── hexo-leancloud-counter-security@1.5.0
├── hexo-neat@1.0.9
├── hexo-pangu@0.2.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@4.0.0
├── hexo-renderer-mathjax@0.6.0
├── hexo-renderer-stylus@2.0.1
├── hexo@5.4.0
├── minimatch@3.0.4
└── prism-themes@1.5.0
```

**Comment by JanWarlen** [comment]
```shell
(node:1105867) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
    at postOperation (/usr/local/dev/station/node_modules/hexo-leancloud-counter-security/index.js:73:10)
    at /usr/local/dev/station/node_modules/hexo-leancloud-counter-security/index.js:151:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1105867) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1105867) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```


```shell
[root@jan-PC station]# node -v
v14.15.3
[root@jan-PC station]# npm -v
8.11.0
[root@jan-PC station]# npm list --depth 0
hexo-site@0.0.0 /usr/local/dev/station
├── babel-runtime@6.26.0
├── hexo-algolia@1.3.2
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-search@2.4.3
├── hexo-generator-tag@1.0.0
├── hexo-leancloud-counter-security@1.5.0
├── hexo-leancloud-counter@0.2.10
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-marked@5.0.0
├── hexo-renderer-stylus@2.1.0
├── hexo-renderer-swig@1.1.0
├── hexo-server@3.0.0
├── hexo-theme-landscape@0.0.3
├── hexo@6.2.0
└── leancloud-storage@4.12.2
```

same problem

data already in database "Counter"

**Comment by JanWarlen** [comment]
> ```shell
> hexo_root/node_modules/hexo-leancloud-counter-security/index.js:73
>     this.log.info('leancloud.memo successfully updated.');
>          ^
> 
> TypeError: Cannot read property 'log' of undefined
>     at postOperation (hexo_root/node_modules/hexo-leancloud-counter-security/index.js:73:10)
>     at /www/page/hexo/node_modules/hexo-leancloud-counter-security/index.js:160:17
>     at processTicksAndRejections (node:internal/process/task_queues:94:5)
> ```
> 
> ```
> ➜  hexo git:(master) ✗ node -v
> v15.8.0
> ➜  hexo git:(master) ✗ npm -v
> 7.6.0
> ➜  hexo git:(master) ✗ npm list --depth 0
> hexo-site@0.0.0 /www/page/hexo
> ├── hexo-deployer-cos-cdn@1.7.1
> ├── hexo-deployer-git@3.0.0
> ├── hexo-filter-mathjax@0.6.3
> ├── hexo-generator-archive@1.0.0
> ├── hexo-generator-baidu-sitemap@0.1.9
> ├── hexo-generator-category@1.0.0
> ├── hexo-generator-feed@3.0.0
> ├── hexo-generator-index@2.0.0
> ├── hexo-generator-search@2.4.1
> ├── hexo-generator-sitemap@2.1.0
> ├── hexo-generator-tag@1.0.0
> ├── hexo-lazyload-image@1.0.10
> ├── hexo-leancloud-counter-security@1.5.0
> ├── hexo-neat@1.0.9
> ├── hexo-pangu@0.2.0
> ├── hexo-renderer-ejs@1.0.0
> ├── hexo-renderer-marked@4.0.0
> ├── hexo-renderer-mathjax@0.6.0
> ├── hexo-renderer-stylus@2.0.1
> ├── hexo@5.4.0
> ├── minimatch@3.0.4
> └── prism-themes@1.5.0
> ```

did you configured git?
when i configured git, it was fixed.
